name = "competition-board"
compatibility_date = "2026-08-18"
pages_build_output_dir = "dist"

[vars]
BLOCK_NON_TW_SITE = "1"
GOOGLE_SHEETS_ENABLED = "1"

[[d1_databases]]
binding = "DB"
database_name = "pjmi-competitions"
database_id = "2d4ce390-882b-4f2f-a681-4abf4f090bc6"
